/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     1

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      false

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x60, 0xC5, 0xA8

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0x00, 0x00, 0x00, 0x00, 0x00 } //60 c5 a8 4e 81 07 36 ac

/*!
 * Application IEEE EUI (big endian)
 * PUT YOUR OWN CODE FROM TTN APP LIKE THAT: { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
 */
#define LORAWAN_APPLICATION_EUI                     { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }

/*!
 * AES encryption/decryption cipher application key
 * PUT YOUR OWN CODE FROM TTN APP LIKE THAT: { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0 }
 */
#define LORAWAN_APPLICATION_KEY                     { 0xe9, 0xee, 0x2c, 0x8c, 0x5f, 0x07, 0xc9, 0xe6, 0x86, 0x28, 0xa4, 0xfa, 0x74, 0xf0, 0x12, 0xf5 }
//e9 ee 2c 8c 5f 07 c9 e6 86 28 a4 fa 74 f0 12 f5

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x00000000

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0xc0, 0xab, 0xb3, 0x0f, 0xe6, 0x86, 0x44, 0xb5, 0x79, 0xc3, 0x7e, 0x5c, 0x61, 0x8b, 0x5b, 0x0b }

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0x86, 0xd4, 0xfc, 0xc0, 0xd4, 0x1c, 0x2f, 0x2c, 0x10, 0x36, 0x9a, 0x52, 0xc4, 0xb3, 0xfa, 0x1b }

#endif // __LORA_COMMISSIONING_H__
